---
- name: ubuntu22 CIS Audit
  hosts: ubuntu22
  become: true
  become_user: root
  roles:
    - role: UBUNTU22-CIS-Audit-devel
      vars:
        setup_audit: true
        run_audit: true
        audit_output_path: "/etc/ansible/log/audit.log"
        audit_done: true
    - role: UBUNTU22-CIS-devel

- name: Configure whitelist setting
  hosts: ubuntu22
  become: true
  tasks:
    - name: Run whitelist_ports tasks
      import_tasks: whitelist_ports.yml
      tags:
        - whitelist_ports
