---
- name: ubuntu24 CIS Audit and Apply CIS Benchmarks
  hosts: ubuntu24
  become: true
  roles:
    - role: UBUNTU24-CIS-Audit-devel

- name: Ensure /etc/motd file exists and install apt packages
  hosts: ubuntu24
  become: true
  tasks:
    - name: Ensure /etc/motd exists
      file:
        path: /etc/motd
        state: touch
        mode: '0644'

- name: ubuntu24 CIS devel
  hosts: ubuntu24
  become: true
  roles:
    - role: UBUNTU24-CIS-devel
